### ISSUE TITLE
Will "qa/dma_buf" branch be upstreamed for QEMU 2.12 release?

### ISSUE THREAD

**Issue by oscarbg** [intel/Igvtg-qemu#3]
Hi GVT team (@kraxel  @TinaZhangZW @yulei-zhang @xiongzha),
as title says do you plan to be ready for upstreaming the dma_buf branch for inclusion on QEMU 2.12 which is within a month away from accepting commits or will have to wait longer to see it in stable releases (say QEMU 2.13?).. do you have some ETA?
I say because the kernel bits are already there in 4.16rc1 and working..

thanks..

**Comment by TerrenceXu** [comment]
Close it since it already upstream.
